# Site settings
title: Code Car Learn Coding!
email: danielawde9@gmail.com
description: CodeCar is application that help you learn coding by gamify learning experience for kids.
url: "http://codecarleb.github.io" # the base hostname & protocol for your site
github_username:  danielawde9
facebook_username: daniel.aoude
linkedin_username: daniel-awde-88250362
twitter_username: DanielAwde
paginate: 4
gems: 
- jekyll-paginate
- jekyll-sitemap
include: ['.editorconfig', '.gitattributes', '.gitignore', '.htaccess']

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Daniel Awde
      layout: "post"
      category: Tech
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"


